# Generated by Django 3.2.8 on 2021-12-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211221_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
